apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-deployment
  labels:
    app: market-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-data
  template:
    metadata:
      labels:
        app: market-data
    spec:
      containers:
      - name: market-data
        image: fo-ai-trading-market-data:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        hostPath:
          path: /data/nifty
          type: DirectoryOrCreate
