version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: trading
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  market-data:
    build: ./services/market-data
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data

  ai-signals:
    build: ./services/ai-signals
    ports:
      - "5004:5000"
    depends_on:
      - postgres
    volumes:
      - ./models:/app/models
      - ./strategies:/app/strategies
      - ./data/live:/data/live

  order-engine:
    build: ./services/order-engine
    ports:
      - "5003:5000"

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:5000"
    depends_on:
      - market-data
      - ai-signals
      - order-engine
      - paper-broker
    environment:
      - EXECUTION_MODE=paper

  dashboard:
    build: ./services/dashboard
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  paper-broker:
    build: ./services/paper-broker
    ports:
      - "5002:5000"
    volumes:
      - ./data/journal:/data

  live-broker:
    build: ./services/live-broker
    ports:
      - "5005:5000"
    environment:
      - Z_KITE_API_KEY=mtb3ovyzkoxwuovq
      - Z_KITE_API_SECRET=uf698sbvsadg1znnukqdr5z47mkpcaaq
      - Z_KITE_ACCESS_TOKEN=tVXABUHlNQT0D8YIzlQTC3Xu3wQQfQ9L

volumes:
  postgres_data:
